locations = (
    "Kippel",
    "Yukon Hotel",
    "Capple Quarters",
    "Thorton Residence",
    "Ennis House",
    "The Bradbury",
    "Animoid Row",
    "Chinatown",
    "Hysteria Hall",
    "Nightclub Row",
    "Gardner Strait",
    "Tyrell Corporation",
    "Polizeipräsidium",
)
